//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usertracking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SeatedModeOn {
            get {
                return ((bool)(this["SeatedModeOn"]));
            }
            set {
                this["SeatedModeOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoHideMenu {
            get {
                return ((bool)(this["AutoHideMenu"]));
            }
            set {
                this["AutoHideMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MouseControlOn {
            get {
                return ((bool)(this["MouseControlOn"]));
            }
            set {
                this["MouseControlOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53.3")]
        public float MonitorWidth {
            get {
                return ((float)(this["MonitorWidth"]));
            }
            set {
                this["MonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float MonitorHeight {
            get {
                return ((float)(this["MonitorHeight"]));
            }
            set {
                this["MonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26.5")]
        public float CamPosX {
            get {
                return ((float)(this["CamPosX"]));
            }
            set {
                this["CamPosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CamPosY {
            get {
                return ((float)(this["CamPosY"]));
            }
            set {
                this["CamPosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public float minMouth4MouseClick {
            get {
                return ((float)(this["minMouth4MouseClick"]));
            }
            set {
                this["minMouth4MouseClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MonitorName {
            get {
                return ((string)(this["MonitorName"]));
            }
            set {
                this["MonitorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMouseControl {
            get {
                return ((bool)(this["EnableMouseControl"]));
            }
            set {
                this["EnableMouseControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseHorizErrorCorrection {
            get {
                return ((bool)(this["UseHorizErrorCorrection"]));
            }
            set {
                this["UseHorizErrorCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float MinHorizErrorThrsh {
            get {
                return ((float)(this["MinHorizErrorThrsh"]));
            }
            set {
                this["MinHorizErrorThrsh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float MaxHorizErrorThrsh {
            get {
                return ((float)(this["MaxHorizErrorThrsh"]));
            }
            set {
                this["MaxHorizErrorThrsh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseVertErrorCorrection {
            get {
                return ((bool)(this["UseVertErrorCorrection"]));
            }
            set {
                this["UseVertErrorCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float MinVertErrorThrsh {
            get {
                return ((float)(this["MinVertErrorThrsh"]));
            }
            set {
                this["MinVertErrorThrsh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float MaxVertErrorThrsh {
            get {
                return ((float)(this["MaxVertErrorThrsh"]));
            }
            set {
                this["MaxVertErrorThrsh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectFacePositionX {
            get {
                return ((float)(this["CorrectFacePositionX"]));
            }
            set {
                this["CorrectFacePositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectFacePositionY {
            get {
                return ((float)(this["CorrectFacePositionY"]));
            }
            set {
                this["CorrectFacePositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectFacePositionZ {
            get {
                return ((float)(this["CorrectFacePositionZ"]));
            }
            set {
                this["CorrectFacePositionZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectFaceOrientationX {
            get {
                return ((float)(this["CorrectFaceOrientationX"]));
            }
            set {
                this["CorrectFaceOrientationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectFaceOrientationY {
            get {
                return ((float)(this["CorrectFaceOrientationY"]));
            }
            set {
                this["CorrectFaceOrientationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectFaceOrientationZ {
            get {
                return ((float)(this["CorrectFaceOrientationZ"]));
            }
            set {
                this["CorrectFaceOrientationZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float SetKinectElevationAngle {
            get {
                return ((float)(this["SetKinectElevationAngle"]));
            }
            set {
                this["SetKinectElevationAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectCursorX {
            get {
                return ((float)(this["CorrectCursorX"]));
            }
            set {
                this["CorrectCursorX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float CorrectCursorY {
            get {
                return ((float)(this["CorrectCursorY"]));
            }
            set {
                this["CorrectCursorY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float minEyebrow4MouseClick {
            get {
                return ((float)(this["minEyebrow4MouseClick"]));
            }
            set {
                this["minEyebrow4MouseClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseEyeBrowClick {
            get {
                return ((bool)(this["UseEyeBrowClick"]));
            }
            set {
                this["UseEyeBrowClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMouthClick {
            get {
                return ((bool)(this["UseMouthClick"]));
            }
            set {
                this["UseMouthClick"] = value;
            }
        }
    }
}
